apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ template "image-resizer.fullname" . }}
  labels:
    app: {{ template "image-resizer.name" . }}
    chart: {{ template "image-resizer.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: {{ .Values.strategy.maxSurge }}
      maxUnavailable: {{ .Values.strategy.maxUnavailable }}
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "image-resizer.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "image-resizer.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: {{ .Values.image.name }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
          {{- range $key, $value := .Values.c_env }}
            - name: {{ $key | upper }}
              value: {{ $value | quote }}
          {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.service.targetPort }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: {{ .Values.service.healthCheck }}
              port: {{ .Values.service.targetPort }}
            initialDelaySeconds: 45
            periodSeconds: 60
            successThreshold: 1
            failureThreshold: 30
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: {{ .Values.service.healthCheck }}
              port: {{ .Values.service.targetPort }}
            initialDelaySeconds: 45
            periodSeconds: 60
            successThreshold: 1
            failureThreshold: 30
            timeoutSeconds: 5
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
