apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ template "image-resizer.fullname" . }}-hpa
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "image-resizer.name" . }}
    chart: {{ template "image-resizer.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ template "image-resizer.fullname" . }}
  minReplicas: {{ .Values.replicaCount }}
  maxReplicas: {{ .Values.maxReplicaCount }}
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: {{ .Values.targetCPUUtilization }}
  - type: Resource
    resource:
      name: memory
      targetAverageUtilization: {{ .Values.targetMemoryUtilization }}